---
name: sops-macos

on:
  push:
    paths:
      - make/apps/sops.mk
      - make/apps/cosign.mk

jobs:
  app:
    uses: ./.github/workflows/common-app-macos.yml
    strategy:
      matrix:
        application:
          - app-sops
    with:
      application: ${{ matrix.application }}
